[2024-09-24 10:24:41,585] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:43,425] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:43,427] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:24:49,374] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:24:49] "GET /pacientes HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:25:01,050] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:25:01] "DELETE /paciente?name=Jhansen HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-24 10:25:04,228] WARNING get_pacientes() L36   Não há pacientes cadastrados no banco de dados :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP 3\app_classifica_problema_cardiaco_api\app.py L36  
[2024-09-24 10:25:04,230] INFO _log() L96   127.0.0.1 - - [24/Sep/2024 10:25:04] "[33mGET /pacientes HTTP/1.1[0m" 404 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
